/**
 * gf_provision — Provision a new VPS gateway pair (primary + standby)
 *
 * Called by the Forge agent when Commander authorizes provisioning.
 * Returns immediately with a provision_request_id; progress is delivered
 * via webhook events. Forge polls gf_pair_status for progress updates.
 *
 * Safety: requires operator confirmation before calling for > 10 accounts.
 */

import type { ClawOpsConfig, OpenClawTool } from '../index';
import axios from 'axios';

export type VpsProvider = 'hetzner' | 'vultr' | 'contabo' | 'hostinger' | 'digitalocean';
export type InstanceTier = 'nano' | 'standard' | 'pro' | 'enterprise';

export interface ProvisionParams {
  /** User account ID to provision for */
  accountId: string;
  /** Service tier — determines VPS size */
  tier: InstanceTier;
  /** Primary provider preference */
  primaryProvider: VpsProvider;
  /** Primary region (e.g. "eu-hetzner-nbg1") */
  primaryRegion: string;
  /** Standby provider (should differ from primary for resilience) */
  standbyProvider: VpsProvider;
  /** Standby region */
  standbyRegion: string;
  /** OpenClaw gateway config to deploy */
  openclawConfig?: Record<string, unknown>;
  /** Tags for the account (passed to GatewayForge) */
  tags?: string[];
  /**
   * Operator confirmation token — required when this is part of a bulk operation
   * affecting > 10 accounts. Generated by Commander when operator says "Go."
   */
  confirmationToken?: string;
}

export interface ProvisionResult {
  provisionRequestId: string;
  accountId: string;
  status: 'QUEUED' | 'CREATING' | 'BOOTSTRAPPING' | 'ACTIVE' | 'FAILED';
  primaryInstanceId: string | null;
  standbyInstanceId: string | null;
  estimatedCompletionSecs: number;
  message: string;
  // Returned immediately — poll gf_pair_status for progress
  trackingUrl: string;
}

export function provisionTool(config: ClawOpsConfig): OpenClawTool {
  return {
    name: 'gf_provision',
    description:
      'Provision a new VPS gateway pair (primary + standby) for a user account. ' +
      'Returns immediately with a tracking ID; use gf_pair_status to monitor progress. ' +
      'Standard provision takes 4–8 minutes. Forge handles retries automatically. ' +
      'SAFETY: Do not call for > 10 accounts without operator confirmationToken. ' +
      'Example: gf_provision({ accountId: "acct-001", tier: "standard", ' +
      'primaryProvider: "hetzner", primaryRegion: "eu-hetzner-nbg1", ' +
      'standbyProvider: "vultr", standbyRegion: "eu-vultr-ams" })',

    inputSchema: {
      type: 'object',
      properties: {
        accountId: {
          type: 'string',
          description: 'User account ID to provision gateway pair for',
        },
        tier: {
          type: 'string',
          enum: ['nano', 'standard', 'pro', 'enterprise'],
          description: 'Service tier (nano=1vCPU/1GB, standard=2vCPU/4GB, pro=4vCPU/8GB, enterprise=8vCPU/16GB)',
        },
        primaryProvider: {
          type: 'string',
          enum: ['hetzner', 'vultr', 'contabo', 'hostinger', 'digitalocean'],
        },
        primaryRegion: {
          type: 'string',
          description: 'Region ID (e.g. eu-hetzner-nbg1, us-vultr-ewr)',
        },
        standbyProvider: {
          type: 'string',
          enum: ['hetzner', 'vultr', 'contabo', 'hostinger', 'digitalocean'],
        },
        standbyRegion: { type: 'string' },
        openclawConfig: {
          type: 'object',
          description: 'OpenClaw gateway configuration to deploy to both instances',
        },
        tags: {
          type: 'array',
          items: { type: 'string' },
          description: 'Optional tags (e.g. ["beta", "companion"])',
        },
        confirmationToken: {
          type: 'string',
          description: 'Required for bulk operations affecting > 10 accounts',
        },
      },
      required: ['accountId', 'tier', 'primaryProvider', 'primaryRegion', 'standbyProvider', 'standbyRegion'],
    },

    execute: async (params: unknown): Promise<ProvisionResult> => {
      const p = params as ProvisionParams;

      const response = await axios.post<ProvisionResult>(
        `${config.gfApiBase}/v1/provision`,
        {
          account_id: p.accountId,
          tier: p.tier,
          primary: {
            provider: p.primaryProvider,
            region: p.primaryRegion,
          },
          standby: {
            provider: p.standbyProvider,
            region: p.standbyRegion,
          },
          openclaw_config: p.openclawConfig ?? {},
          tags: p.tags ?? [],
          confirmation_token: p.confirmationToken,
        },
        {
          headers: {
            Authorization: `Bearer ${config.gfApiKey}`,
            'Content-Type': 'application/json',
          },
          timeout: 15_000,
        }
      );

      return response.data;
    },
  };
}
