#!/usr/bin/env bash
# GatewayForge gf-clawnode installer
# Usage: curl -fsSL https://raw.githubusercontent.com/redclaw/clawops/main/deploy/scripts/install.sh | bash
#
# Environment variables:
#   CLAWOPS_VERSION   — Release tag to install (default: latest)
#   INSTANCE_ID       — Required: unique UUID for this instance
#   GATEWAY_URL       — Required: OpenClaw gateway WebSocket URL
#   GF_API_KEY        — Required: GatewayForge API key
#   NODE_PROVIDER     — VPS provider (hetzner|vultr|contabo|hostinger|digitalocean)
#   NODE_REGION       — Region code (e.g. eu-hetzner-nbg1)
#   NODE_TIER         — Service tier (nano|standard|pro|enterprise)
#   NODE_ROLE         — Instance role (primary|standby)
#   ACCOUNT_ID        — User account ID

set -euo pipefail

REPO="redclaw/clawops"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/gf-clawnode"
LOG_DIR="/var/log/gf-clawnode"
DATA_DIR="/var/lib/gf-clawnode"
SERVICE_NAME="clawops-node"
BINARY_NAME="gf-clawnode"
SERVICE_USER="clawnode"

# ─── Helpers ──────────────────────────────────────────────────────────────────

info()  { echo "[INFO]  $*"; }
warn()  { echo "[WARN]  $*" >&2; }
error() { echo "[ERROR] $*" >&2; exit 1; }

require_env() {
    local var="$1"
    if [[ -z "${!var:-}" ]]; then
        error "Required environment variable $var is not set"
    fi
}

require_root() {
    if [[ "$(id -u)" != "0" ]]; then
        error "This script must be run as root. Use: sudo bash install.sh"
    fi
}

detect_arch() {
    local arch
    arch="$(uname -m)"
    case "$arch" in
        x86_64)  echo "x86_64" ;;
        aarch64) echo "aarch64" ;;
        arm64)   echo "aarch64" ;;
        *)       error "Unsupported architecture: $arch" ;;
    esac
}

get_latest_version() {
    curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
        | grep '"tag_name"' \
        | sed -E 's/.*"tag_name": *"([^"]+)".*/\1/'
}

# ─── Main ─────────────────────────────────────────────────────────────────────

main() {
    require_root

    info "=== GatewayForge gf-clawnode installer ==="

    # Validate required config
    require_env INSTANCE_ID
    require_env GATEWAY_URL
    require_env GF_API_KEY

    local version="${CLAWOPS_VERSION:-}"
    if [[ -z "$version" ]]; then
        info "Fetching latest release version..."
        version="$(get_latest_version)"
        info "Latest version: $version"
    fi

    local arch
    arch="$(detect_arch)"
    local binary_url="https://github.com/${REPO}/releases/download/${version}/${BINARY_NAME}-linux-${arch}"

    info "Installing gf-clawnode $version for linux/${arch}"

    # Create system user
    if ! id -u "$SERVICE_USER" &>/dev/null; then
        info "Creating system user: $SERVICE_USER"
        useradd -r -s /bin/false -M -d /nonexistent "$SERVICE_USER"
    fi

    # Create directories
    mkdir -p "$CONFIG_DIR" "$LOG_DIR" "$DATA_DIR"
    chown "$SERVICE_USER:$SERVICE_USER" "$LOG_DIR" "$DATA_DIR"
    chmod 750 "$CONFIG_DIR" "$LOG_DIR" "$DATA_DIR"

    # Download binary
    info "Downloading $binary_url ..."
    local tmp_bin
    tmp_bin="$(mktemp /tmp/gf-clawnode.XXXXXX)"
    curl -fsSL "$binary_url" -o "$tmp_bin"
    chmod +x "$tmp_bin"

    # Verify binary works
    if ! "$tmp_bin" --help &>/dev/null; then
        error "Downloaded binary failed to run — check architecture compatibility"
    fi

    # Install binary
    mv "$tmp_bin" "${INSTALL_DIR}/${BINARY_NAME}"
    info "Binary installed to ${INSTALL_DIR}/${BINARY_NAME}"

    # Write config file
    info "Writing config to ${CONFIG_DIR}/config.toml"
    cat > "${CONFIG_DIR}/config.toml" <<CONFIG_EOF
# gf-clawnode configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

instance_id = "${INSTANCE_ID}"
gateway_url = "${GATEWAY_URL}"
api_key = "${GF_API_KEY}"
gf_api_base = "${GF_API_BASE:-https://api.gatewayforge.io}"
provider = "${NODE_PROVIDER:-hetzner}"
region = "${NODE_REGION:-eu-hetzner-nbg1}"
tier = "${NODE_TIER:-standard}"
role = "${NODE_ROLE:-primary}"
account_id = "${ACCOUNT_ID:-}"
pair_instance_id = "${PAIR_INSTANCE_ID:-}"
heartbeat_interval_secs = 30
metrics_interval_secs = 60

allowed_command_prefixes = [
    "vps.",
    "openclaw.",
    "config.",
    "docker.",
    "ssh.",
    "firewall.",
    "tailscale.",
]
CONFIG_EOF
    chmod 600 "${CONFIG_DIR}/config.toml"
    chown "$SERVICE_USER:$SERVICE_USER" "${CONFIG_DIR}/config.toml"

    # Install systemd service
    local service_src
    service_src="$(dirname "$0")/../systemd/clawops-node.service"
    if [[ -f "$service_src" ]]; then
        info "Installing systemd service from $service_src"
        cp "$service_src" "/etc/systemd/system/${SERVICE_NAME}.service"
    else
        info "Writing built-in systemd service unit"
        cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<SERVICE_EOF
[Unit]
Description=GatewayForge ClawNode Agent
After=network-online.target docker.service
Wants=network-online.target
Requires=docker.service

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
EnvironmentFile=-${CONFIG_DIR}/env
Environment=RUST_LOG=gf_clawnode=info
ExecStart=${INSTALL_DIR}/${BINARY_NAME} --config ${CONFIG_DIR}/config.toml
Restart=always
RestartSec=10s
StandardOutput=journal
StandardError=journal
SyslogIdentifier=gf-clawnode
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${LOG_DIR} ${DATA_DIR}
ReadOnlyPaths=${CONFIG_DIR}

[Install]
WantedBy=multi-user.target
SERVICE_EOF
    fi

    # Enable and start service
    info "Enabling and starting $SERVICE_NAME service..."
    systemctl daemon-reload
    systemctl enable "$SERVICE_NAME"
    systemctl restart "$SERVICE_NAME"

    sleep 3

    if systemctl is-active --quiet "$SERVICE_NAME"; then
        info "=== gf-clawnode $version installed and running ==="
        info "Status: systemctl status $SERVICE_NAME"
        info "Logs:   journalctl -u $SERVICE_NAME -f"
    else
        warn "Service started but may have issues. Check: journalctl -u $SERVICE_NAME -n 50"
    fi
}

main "$@"
